#!/usr/bin/env bash
# nixos_config.sh — Generate /etc/nixos/configuration.nix from installer config
source "${LIB_DIR}/protection.sh"

# generate_nixos_config — Build the full configuration.nix
generate_nixos_config() {
    local config_dir="${MOUNTPOINT}/etc/nixos"
    mkdir -p "${config_dir}"

    einfo "Generating configuration.nix..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would generate configuration.nix"
        _write_configuration_nix
        return 0
    fi

    _write_configuration_nix > "${config_dir}/configuration.nix"
    einfo "configuration.nix generated"
}

# run_nixos_generate_config — Let NixOS detect hardware
run_nixos_generate_config() {
    einfo "Running nixos-generate-config..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would run nixos-generate-config"
        return 0
    fi

    try "Generating hardware configuration" \
        nixos-generate-config --root "${MOUNTPOINT}"

    # Back up the generated hardware-configuration.nix
    if [[ -f "${MOUNTPOINT}/etc/nixos/hardware-configuration.nix" ]]; then
        einfo "hardware-configuration.nix generated by NixOS"
    fi
}

# run_nixos_install — Execute nixos-install
run_nixos_install() {
    einfo "Running nixos-install..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would run nixos-install"
        return 0
    fi

    try "Installing NixOS" nixos-install --root "${MOUNTPOINT}" --no-root-passwd

    einfo "nixos-install completed"
}

# set_nixos_passwords — Set passwords after install
set_nixos_passwords() {
    einfo "Setting user passwords..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would set passwords"
        return 0
    fi

    # Root password
    if [[ "${ROOT_PASSWORD_SET:-}" == "yes" ]]; then
        einfo "You will be prompted to set the root password."
        nixos-enter --root "${MOUNTPOINT}" -- passwd root
    fi

    # User password
    if [[ -n "${USERNAME:-}" && "${USER_PASSWORD_SET:-}" == "yes" ]]; then
        einfo "You will be prompted to set the password for ${USERNAME}."
        nixos-enter --root "${MOUNTPOINT}" -- passwd "${USERNAME}"
    fi
}

# _write_configuration_nix — Output the full configuration.nix
_write_configuration_nix() {
    cat << 'NIXHEAD'
# /etc/nixos/configuration.nix
# Generated by NixOS TUI Installer
# Edit this file to define your system configuration.
# Run `sudo nixos-rebuild switch` after changes.

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix
  ];

NIXHEAD

    # --- Bootloader ---
    _nix_bootloader

    # --- Kernel ---
    _nix_kernel

    # --- Swap ---
    _nix_swap

    # --- Networking ---
    _nix_networking

    # --- Locale / Timezone ---
    _nix_locale

    # --- Users ---
    _nix_users

    # --- Desktop ---
    _nix_desktop

    # --- Hyprland ecosystem ---
    _nix_hyprland

    # --- GPU ---
    _nix_gpu

    # --- Audio ---
    _nix_audio

    # --- System packages ---
    _nix_packages

    # --- Peripherals ---
    _nix_peripherals

    # --- Services ---
    _nix_services

    # --- Nix settings ---
    _nix_settings

    # --- State version ---
    local state_ver="${NIXOS_CHANNEL##*-}"
    # For nixos-unstable, read version from the running system
    if [[ "${state_ver}" == "unstable" ]]; then
        state_ver=$(nixos-version 2>/dev/null | sed 's/\([0-9]*\.[0-9]*\).*/\1/') || state_ver="24.11"
        [[ -z "${state_ver}" || ! "${state_ver}" =~ ^[0-9]+\.[0-9]+$ ]] && state_ver="24.11"
    fi
    cat << NIXFOOT

  # DO NOT CHANGE — tracks the NixOS release at install time
  system.stateVersion = "${state_ver}";
}
NIXFOOT
}

_nix_kernel() {
    case "${KERNEL_PACKAGE:-default}" in
        latest)
            echo "  boot.kernelPackages = pkgs.linuxPackages_latest;"
            echo "" ;;
        lts)
            echo "  boot.kernelPackages = pkgs.linuxPackages;"
            echo "" ;;
        zen)
            echo "  boot.kernelPackages = pkgs.linuxPackages_zen;"
            echo "" ;;
    esac
}

_nix_swap() {
    case "${SWAP_TYPE:-none}" in
        zram)
            cat << 'NIX'
  # Swap: zram
  zramSwap.enable = true;

NIX
            ;;
    esac
}

_nix_bootloader() {
    if [[ "${BOOTLOADER_TYPE:-systemd-boot}" == "grub" ]]; then
        cat << 'NIX'
  # --- Bootloader (GRUB — multi-boot support) ---
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.useOSProber = true;
  boot.loader.efi.canTouchEfiVariables = true;
NIX
    else
        cat << 'NIX'
  # --- Bootloader ---
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
NIX
    fi

    if [[ "${ENCRYPTION:-none}" == "luks" ]]; then
        local luks_uuid
        luks_uuid=$(get_uuid "${LUKS_PARTITION}")
        cat << NIX

  # LUKS encryption
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/${luks_uuid}";
  };
NIX
    fi

    echo ""
}

_nix_networking() {
    cat << NIX
  # --- Networking ---
  networking.hostName = "${HOSTNAME:-nixos}";
  networking.networkmanager.enable = true;
NIX

    if [[ "${ENABLE_SSH:-no}" == "yes" ]]; then
        cat << 'NIX'
  services.openssh.enable = true;
  services.openssh.settings.PermitRootLogin = "prohibit-password";
NIX
    fi

    echo ""
}

_nix_locale() {
    local tz="${TIMEZONE:-Europe/Warsaw}"
    local loc="${LOCALE:-en_US.UTF-8}"
    local km="${KEYMAP:-us}"

    cat << NIX
  # --- Locale & Timezone ---
  time.timeZone = "${tz}";
  i18n.defaultLocale = "${loc}";
  i18n.extraLocaleSettings = {
    LC_MESSAGES = "${loc}";
    LC_TIME = "${loc}";
  };
  console.keyMap = "${km}";
NIX

    echo ""
}

_nix_users() {
    cat << 'NIX'
  # --- Users ---
  users.mutableUsers = true;
NIX

    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,networkmanager,audio,video}"
        # Convert comma-separated to nix list
        local nix_groups
        nix_groups=$(echo "${groups}" | tr ',' '\n' | sed 's/^/    "/' | sed 's/$/"/')

        cat << NIX

  users.users.${USERNAME} = {
    isNormalUser = true;
    description = "${USERNAME}";
    extraGroups = [
${nix_groups}
    ];
    initialPassword = "${USERNAME}";
  };
NIX
    fi

    echo ""
}

_nix_hyprland() {
    if [[ "${ENABLE_HYPRLAND:-no}" != "yes" ]]; then
        return 0
    fi
    cat << 'NIX'
  # --- Hyprland ecosystem ---
  programs.hyprland = {
    enable = true;
    xwayland.enable = true;
  };
NIX

    echo ""
}

_nix_desktop() {
    local desktop="${DESKTOP_TYPE:-kde}"

    if [[ "${desktop}" == "gnome" ]]; then
        cat << 'NIX'
  # --- Desktop: GNOME ---
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.displayManager.gdm.wayland = true;
  services.desktopManager.gnome.enable = true;

  # XDG portal for Wayland
  xdg.portal.enable = true;
NIX
    else
        cat << 'NIX'
  # --- Desktop: KDE Plasma ---
  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;
  services.desktopManager.plasma6.enable = true;

  # XDG portal for Wayland
  xdg.portal.enable = true;
NIX
    fi

    if [[ "${ENABLE_PRINTING:-no}" == "yes" ]]; then
        cat << 'NIX'

  # Printing
  services.printing.enable = true;
NIX
    fi

    if [[ "${ENABLE_BLUETOOTH:-no}" == "yes" ]]; then
        cat << 'NIX'

  # Bluetooth
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
NIX
    fi

    echo ""
}

_nix_gpu() {
    local vendor="${GPU_VENDOR:-unknown}"

    case "${vendor}" in
        nvidia)
            cat << 'NIX'
  # --- GPU: NVIDIA ---
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    nvidiaSettings = true;
NIX
            if [[ "${GPU_NVIDIA_OPEN:-no}" == "yes" ]]; then
                cat << 'NIX'
    open = true;
NIX
            else
                cat << 'NIX'
    open = false;
NIX
            fi
            cat << 'NIX'
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
NIX

            # Hybrid GPU: NVIDIA PRIME offload
            if [[ "${HYBRID_GPU:-no}" == "yes" ]]; then
                local igpu_bus="${IGPU_BUS_ID:-}"
                local dgpu_bus="${DGPU_BUS_ID:-}"
                cat << 'NIX'

  # Hybrid GPU: NVIDIA PRIME render offload
  hardware.nvidia.prime = {
NIX
                if [[ "${IGPU_VENDOR:-}" == "intel" && -n "${igpu_bus}" ]]; then
                    echo "    intelBusId = \"${igpu_bus}\";"
                elif [[ "${IGPU_VENDOR:-}" == "amd" && -n "${igpu_bus}" ]]; then
                    echo "    amdgpuBusId = \"${igpu_bus}\";"
                fi
                [[ -n "${dgpu_bus}" ]] && echo "    nvidiaBusId = \"${dgpu_bus}\";"
                cat << 'NIX'
    offload = {
      enable = true;
      enableOffloadCmd = true;
    };
  };
NIX
            fi
            ;;
        amd)
            cat << 'NIX'
  # --- GPU: AMD ---
  hardware.graphics.enable = true;
  hardware.graphics.extraPackages = with pkgs; [
    amdvlk
    rocmPackages.clr.icd
  ];
NIX
            ;;
        intel)
            cat << 'NIX'
  # --- GPU: Intel ---
  hardware.graphics.enable = true;
  hardware.graphics.extraPackages = with pkgs; [
    intel-media-driver
    vaapiIntel
  ];
NIX
            ;;
    esac

    echo ""
}

_nix_peripherals() {
    local has_peripherals=0

    if [[ "${ENABLE_FINGERPRINT:-no}" == "yes" ]]; then
        has_peripherals=1
        cat << 'NIX'

  # Fingerprint reader
  services.fprintd.enable = true;
NIX
    fi

    if [[ "${ENABLE_THUNDERBOLT:-no}" == "yes" ]]; then
        has_peripherals=1
        cat << 'NIX'

  # Thunderbolt
  services.hardware.bolt.enable = true;
NIX
    fi

    if [[ "${ENABLE_SENSORS:-no}" == "yes" ]]; then
        has_peripherals=1
        cat << 'NIX'

  # IIO sensor proxy (2-in-1 tablets)
  hardware.sensor.iio.enable = true;
NIX
    fi

    if [[ "${ENABLE_WWAN:-no}" == "yes" ]]; then
        has_peripherals=1
        cat << 'NIX'

  # WWAN/LTE modem
  services.modemManager.enable = true;
NIX
    fi

    [[ ${has_peripherals} -eq 1 ]] && echo ""
}

_nix_audio() {
    cat << 'NIX'
  # --- Audio: PipeWire ---
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    wireplumber.enable = true;
  };
NIX

    echo ""
}

_nix_packages() {
    cat << 'NIX'
  # --- System packages ---
  environment.systemPackages = with pkgs; [
    # Core tools
    vim
    wget
    curl
    git
    htop
    unzip
    file
    pciutils
    usbutils
NIX

    # Hyprland ecosystem packages
    if [[ "${ENABLE_HYPRLAND:-no}" == "yes" ]]; then
        cat << 'NIX'
    # Hyprland ecosystem
    hyprpaper
    hypridle
    hyprlock
    waybar
    wofi
    mako
    grim
    slurp
    wl-clipboard
    brightnessctl
NIX
    fi

    # Desktop extras
    local extras="${DESKTOP_EXTRAS:-}"
    if [[ -n "${extras}" ]]; then
        local pkg
        local cleaned
        cleaned=$(echo "${extras}" | tr -d '"')
        for pkg in ${cleaned}; do
            echo "    ${pkg}"
        done
    fi

    # Extra packages from user
    if [[ -n "${EXTRA_PACKAGES:-}" ]]; then
        local pkg
        for pkg in ${EXTRA_PACKAGES}; do
            echo "    ${pkg}"
        done
    fi

    cat << 'NIX'
  ];
NIX

    if [[ "${ENABLE_FLATPAK:-no}" == "yes" ]]; then
        cat << 'NIX'

  # Flatpak
  services.flatpak.enable = true;
NIX
    fi

    echo ""
}

_nix_services() {
    cat << 'NIX'
  # --- Misc services ---
  services.fwupd.enable = true;
NIX

    if [[ "${ENABLE_ASUSCTL:-no}" == "yes" ]]; then
        cat << 'NIX'

  # ASUS ROG/TUF support
  services.asusd.enable = true;
  services.asusd.enableUserService = true;
NIX
    fi

    echo ""
}

_nix_settings() {
    if [[ "${USE_FLAKES:-yes}" == "yes" ]]; then
        cat << 'NIX'
  # --- Nix settings ---
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };
NIX
    else
        cat << 'NIX'
  # --- Nix settings ---
  nix.settings = {
    auto-optimise-store = true;
  };
NIX
    fi
    cat << 'NIX'

  # Garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  # Allow unfree packages (NVIDIA drivers, etc.)
  nixpkgs.config.allowUnfree = true;
NIX

    echo ""
}
