#!/usr/bin/env bash
# nixos_config.sh — Generate /etc/nixos/configuration.nix from installer config
source "${LIB_DIR}/protection.sh"

# generate_nixos_config — Build the full configuration.nix
generate_nixos_config() {
    local config_dir="${MOUNTPOINT}/etc/nixos"
    mkdir -p "${config_dir}"

    einfo "Generating configuration.nix..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would generate configuration.nix"
        _write_configuration_nix
        return 0
    fi

    _write_configuration_nix > "${config_dir}/configuration.nix"
    einfo "configuration.nix generated"
}

# run_nixos_generate_config — Let NixOS detect hardware
run_nixos_generate_config() {
    einfo "Running nixos-generate-config..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would run nixos-generate-config"
        return 0
    fi

    try "Generating hardware configuration" \
        nixos-generate-config --root "${MOUNTPOINT}"

    # Back up the generated hardware-configuration.nix
    if [[ -f "${MOUNTPOINT}/etc/nixos/hardware-configuration.nix" ]]; then
        einfo "hardware-configuration.nix generated by NixOS"
    fi
}

# run_nixos_install — Execute nixos-install
run_nixos_install() {
    einfo "Running nixos-install..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would run nixos-install"
        return 0
    fi

    try "Installing NixOS" nixos-install --root "${MOUNTPOINT}" --no-root-passwd

    einfo "nixos-install completed"
}

# set_nixos_passwords — Set passwords after install
set_nixos_passwords() {
    einfo "Setting user passwords..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would set passwords"
        return 0
    fi

    # nixos-enter modifies PATH (chroot environment). Save and restore
    # to prevent host commands (date, ls) from disappearing after exit.
    local saved_path="${PATH}"

    # Root password
    if [[ "${ROOT_PASSWORD_SET:-}" == "yes" ]]; then
        einfo "You will be prompted to set the root password."
        nixos-enter --root "${MOUNTPOINT}" -- passwd root </dev/tty
        export PATH="${saved_path}"
    fi

    # User password
    if [[ -n "${USERNAME:-}" && "${USER_PASSWORD_SET:-}" == "yes" ]]; then
        einfo "You will be prompted to set the password for ${USERNAME}."
        nixos-enter --root "${MOUNTPOINT}" -- passwd "${USERNAME}" </dev/tty
        export PATH="${saved_path}"
    fi
}

# _write_configuration_nix — Output the full configuration.nix
_write_configuration_nix() {
    cat << 'NIXHEAD'
# /etc/nixos/configuration.nix
# Generated by NixOS TUI Installer
# Edit this file to define your system configuration.
# Run `sudo nixos-rebuild switch` after changes.

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix
  ];

NIXHEAD

    # --- Bootloader ---
    _nix_bootloader

    # --- Kernel ---
    _nix_kernel

    # --- CPU microcode ---
    _nix_microcode

    # --- UMPC quirks (GPD/Chuwi portrait panels, ALC287, GPD fan) ---
    _nix_umpc

    # --- Swap ---
    _nix_swap

    # --- Networking ---
    _nix_networking

    # --- Locale / Timezone ---
    _nix_locale

    # --- Users ---
    _nix_users

    # --- Desktop ---
    _nix_desktop

    # --- Hyprland ecosystem ---
    _nix_hyprland

    # --- GPU ---
    _nix_gpu

    # --- Audio ---
    _nix_audio

    # --- System packages ---
    _nix_packages

    # --- Peripherals ---
    _nix_peripherals

    # --- Services ---
    _nix_services

    # --- Nix settings ---
    _nix_settings

    # --- State version ---
    local state_ver="${NIXOS_CHANNEL##*-}"
    # For nixos-unstable, read version from the running system
    if [[ "${state_ver}" == "unstable" ]]; then
        state_ver=$(nixos-version 2>/dev/null | sed 's/\([0-9]*\.[0-9]*\).*/\1/') || state_ver="24.11"
        [[ -z "${state_ver}" || ! "${state_ver}" =~ ^[0-9]+\.[0-9]+$ ]] && state_ver="24.11"
    fi
    cat << NIXFOOT

  # DO NOT CHANGE — tracks the NixOS release at install time
  system.stateVersion = "${state_ver}";
}
NIXFOOT
}

_nix_kernel() {
    case "${KERNEL_PACKAGE:-default}" in
        latest)
            echo "  boot.kernelPackages = pkgs.linuxPackages_latest;"
            echo "" ;;
        lts)
            echo "  boot.kernelPackages = pkgs.linuxPackages;"
            echo "" ;;
        zen)
            echo "  boot.kernelPackages = pkgs.linuxPackages_zen;"
            echo "" ;;
    esac
}

# _nix_microcode — CPU microcode updates (security/stability fixes from the CPU
# vendor). Pulled from redistributable firmware; enabling it is recommended on
# all real hardware. Vendor inferred from CPU_MARCH (set by detect_cpu).
_nix_microcode() {
    case "${CPU_MARCH:-generic}" in
        intel)
            echo "  hardware.enableRedistributableFirmware = true;"
            echo "  hardware.cpu.intel.updateMicrocode = true;"
            echo "" ;;
        amd)
            echo "  hardware.enableRedistributableFirmware = true;"
            echo "  hardware.cpu.amd.updateMicrocode = true;"
            echo "" ;;
    esac
}

# _nix_umpc — Declarative UMPC quirks for GPD Pocket/Win and Chuwi MiniBook X.
# NixOS is declarative: instead of writing scripts into the target system (as
# the Gentoo installer does in lib/umpc.sh), everything is expressed as Nix
# attributes that nixos-install materializes.
#   - Panel rotation: boot.kernelParams (fbcon=rotate + video=...:panel_orientation)
#   - ALC287 Auto-Mute disable: systemd.services.alc287-unmute (oneshot)
#   - SDDM X11 greeter rotation: services.xserver.displayManager.setupCommands (xrandr)
#   - GPD fan: a comment pointing at gpd-fan-daemon (no auto-install, declarative)
_nix_umpc() {
    [[ "${UMPC_DETECTED:-0}" == "1" ]] || return 0

    echo "  # --- UMPC quirks: ${UMPC_VENDOR} ${UMPC_MODEL} ---"

    # Panel rotation (MOST IMPORTANT): fbcon for early console + panel_orientation
    # for KMS-aware compositors (KWin, Mutter). Without this the first boot shows
    # the image rotated because the panel is mounted physically rotated relative
    # to the casing. Only emit when a panel orientation was determined.
    if [[ -n "${UMPC_PANEL_ORIENTATION:-}" ]]; then
        echo "  boot.kernelParams = ["
        echo "    \"fbcon=rotate:${UMPC_FBCON_ROTATE}\""
        echo "    \"video=${UMPC_VIDEO_CONNECTOR}:panel_orientation=${UMPC_PANEL_ORIENTATION}\""
        echo "  ];"
    fi

    # ALC287 Auto-Mute disable. ALC287 on Pocket 4 (and many AMD Phoenix
    # laptops) ships with Auto-Mute enabled, which routes audio nowhere unless
    # a headphone jack is sensed correctly — jack detection on this codec is
    # unreliable, so speakers stay silent. Fix: disable Auto-Mute via amixer at
    # boot. Declared as a oneshot systemd unit so it runs every boot after the
    # sound stack is up. amixer comes from pkgs.alsa-utils referenced directly.
    if [[ "${UMPC_ALC287_QUIRK:-0}" == "1" ]]; then
        cat << 'NIX'

  # ALC287 Auto-Mute disable (UMPC speakers are silent without this).
  systemd.services.alc287-unmute = {
    description = "Disable ALC287 Auto-Mute and unmute outputs";
    after = [ "sound.target" ];
    wants = [ "sound.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      ${pkgs.alsa-utils}/bin/amixer -c 0 sset 'Auto-Mute Mode' Disabled || true
      for ctl in 'Master' 'Speaker' 'Headphone' 'PCM'; do
        ${pkgs.alsa-utils}/bin/amixer -c 0 sset "$ctl" unmute || true
        ${pkgs.alsa-utils}/bin/amixer -c 0 sset "$ctl" '100%' || true
      done
    '';
  };
NIX
    fi

    # SDDM X11 greeter rotation. The kernel panel_orientation quirk rotates the
    # fbcon console and is honored by Wayland sessions, but SDDM's greeter runs
    # on Xorg which ignores panel_orientation — so the login screen alone stays
    # portrait. Rotate it with xrandr via setupCommands. Xorg names the panel
    # without the DRM suffix (e.g. "eDP" not "eDP-1"), so auto-detect the
    # connected output. fbcon rotate -> xrandr: 1=right, 2=inverted, 3=left.
    if [[ -n "${UMPC_FBCON_ROTATE:-}" && "${UMPC_FBCON_ROTATE}" != "0" ]]; then
        local rot=""
        case "${UMPC_FBCON_ROTATE}" in
            1) rot="right" ;;
            2) rot="inverted" ;;
            3) rot="left" ;;
        esac
        if [[ -n "${rot}" ]]; then
            cat << NIX

  # Rotate the SDDM X11 greeter to match the UMPC panel (Xorg ignores the
  # kernel panel_orientation quirk; the Wayland session honors it on its own).
  services.xserver.displayManager.setupCommands = ''
    _out=\$(\${pkgs.xorg.xrandr}/bin/xrandr | \${pkgs.gawk}/bin/awk '/ connected/{print \$1; exit}')
    [ -n "\$_out" ] && \${pkgs.xorg.xrandr}/bin/xrandr --output "\$_out" --rotate ${rot}
  '';
NIX
        fi
    fi

    # GPD fan: NixOS is declarative and there is no in-tree gpd-fan-daemon
    # module, so emit guidance rather than a POST-INSTALL script. Fans run on
    # ACPI defaults until the daemon is set up (usable, just louder).
    if [[ "${UMPC_GPD_FAN:-0}" == "1" ]]; then
        cat << 'NIX'

  # GPD fan control: fans currently run on ACPI defaults (louder than Windows).
  # For smarter fan curves, package gpd-fan-driver (kernel module) +
  # gpd-fan-daemon (https://github.com/Cryolitia/gpd-fan-daemon) as a Nix
  # overlay/derivation and run it via a systemd service, or check whether a
  # `hardware.gpd`-style option exists in your nixpkgs revision.
NIX
    fi

    echo ""
}

_nix_swap() {
    case "${SWAP_TYPE:-none}" in
        zram)
            cat << 'NIX'
  # Swap: zram
  zramSwap.enable = true;

NIX
            ;;
    esac
}

_nix_bootloader() {
    if [[ "${BOOTLOADER_TYPE:-systemd-boot}" == "grub" ]]; then
        cat << 'NIX'
  # --- Bootloader (GRUB — multi-boot support) ---
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.useOSProber = true;
  boot.loader.efi.canTouchEfiVariables = true;
NIX
    else
        cat << 'NIX'
  # --- Bootloader ---
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
NIX
    fi

    if [[ "${ENCRYPTION:-none}" == "luks" ]]; then
        local luks_uuid
        luks_uuid=$(get_uuid "${LUKS_PARTITION}")
        cat << NIX

  # LUKS encryption
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/${luks_uuid}";
  };
NIX
    fi

    echo ""
}

_nix_networking() {
    cat << NIX
  # --- Networking ---
  networking.hostName = "${HOSTNAME:-nixos}";
  networking.networkmanager.enable = true;
NIX

    if [[ "${ENABLE_SSH:-no}" == "yes" ]]; then
        cat << 'NIX'
  services.openssh.enable = true;
  services.openssh.settings.PermitRootLogin = "prohibit-password";
NIX
    fi

    echo ""
}

_nix_locale() {
    local tz="${TIMEZONE:-Europe/Warsaw}"
    local loc="${LOCALE:-en_US.UTF-8}"
    local km="${KEYMAP:-us}"

    cat << NIX
  # --- Locale & Timezone ---
  time.timeZone = "${tz}";
  i18n.defaultLocale = "${loc}";
  i18n.extraLocaleSettings = {
    LC_MESSAGES = "${loc}";
    LC_TIME = "${loc}";
  };
  console.keyMap = "${km}";
NIX

    echo ""
}

_nix_users() {
    cat << 'NIX'
  # --- Users ---
  users.mutableUsers = true;
NIX

    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,networkmanager,audio,video}"
        # Convert comma-separated to nix list
        local nix_groups
        nix_groups=$(echo "${groups}" | tr ',' '\n' | sed 's/^/    "/' | sed 's/$/"/')

        cat << NIX

  users.users.${USERNAME} = {
    isNormalUser = true;
    description = "${USERNAME}";
    extraGroups = [
${nix_groups}
    ];
    # Password set interactively via set_nixos_passwords() after install
  };
NIX
    fi

    echo ""
}

_nix_hyprland() {
    if [[ "${ENABLE_HYPRLAND:-no}" != "yes" ]]; then
        return 0
    fi
    cat << 'NIX'
  # --- Hyprland ecosystem ---
  programs.hyprland = {
    enable = true;
    xwayland.enable = true;
  };
NIX

    echo ""
}

_nix_desktop() {
    local desktop="${DESKTOP_TYPE:-kde}"

    if [[ "${desktop}" == "gnome" ]]; then
        cat << 'NIX'
  # --- Desktop: GNOME ---
  services.displayManager.gdm.enable = true;
  services.displayManager.gdm.wayland = true;
  services.desktopManager.gnome.enable = true;

  # XDG portal for Wayland
  xdg.portal.enable = true;
NIX
    else
        cat << 'NIX'
  # --- Desktop: KDE Plasma ---
  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;
  services.desktopManager.plasma6.enable = true;

  # XDG portal for Wayland
  xdg.portal.enable = true;
NIX
    fi

    if [[ "${ENABLE_PRINTING:-no}" == "yes" ]]; then
        cat << 'NIX'

  # Printing
  services.printing.enable = true;
NIX
    fi

    if [[ "${ENABLE_BLUETOOTH:-no}" == "yes" ]]; then
        cat << 'NIX'

  # Bluetooth
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
NIX
    fi

    echo ""
}

_nix_gpu() {
    local vendor="${GPU_VENDOR:-unknown}"

    case "${vendor}" in
        nvidia)
            cat << 'NIX'
  # --- GPU: NVIDIA ---
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    nvidiaSettings = true;
NIX
            if [[ "${GPU_NVIDIA_OPEN:-no}" == "yes" ]]; then
                cat << 'NIX'
    open = true;
NIX
            else
                cat << 'NIX'
    open = false;
NIX
            fi
            cat << 'NIX'
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
NIX

            # Hybrid GPU: NVIDIA PRIME offload
            if [[ "${HYBRID_GPU:-no}" == "yes" ]]; then
                local igpu_bus="${IGPU_BUS_ID:-}"
                local dgpu_bus="${DGPU_BUS_ID:-}"
                cat << 'NIX'

  # Hybrid GPU: NVIDIA PRIME render offload
  hardware.nvidia.prime = {
NIX
                if [[ "${IGPU_VENDOR:-}" == "intel" && -n "${igpu_bus}" ]]; then
                    echo "    intelBusId = \"${igpu_bus}\";"
                elif [[ "${IGPU_VENDOR:-}" == "amd" && -n "${igpu_bus}" ]]; then
                    echo "    amdgpuBusId = \"${igpu_bus}\";"
                fi
                [[ -n "${dgpu_bus}" ]] && echo "    nvidiaBusId = \"${dgpu_bus}\";"
                cat << 'NIX'
    offload = {
      enable = true;
      enableOffloadCmd = true;
    };
  };
NIX
            fi
            ;;
        amd)
            cat << 'NIX'
  # --- GPU: AMD ---
  hardware.graphics.enable = true;
  hardware.graphics.extraPackages = with pkgs; [
    amdvlk
    rocmPackages.clr.icd
  ];
NIX
            ;;
        intel)
            cat << 'NIX'
  # --- GPU: Intel ---
  hardware.graphics.enable = true;
  hardware.graphics.extraPackages = with pkgs; [
    intel-media-driver
    intel-vaapi-driver
  ];
NIX
            ;;
    esac

    echo ""
}

_nix_peripherals() {
    local has_peripherals=0

    if [[ "${ENABLE_FINGERPRINT:-no}" == "yes" ]]; then
        has_peripherals=1
        cat << 'NIX'

  # Fingerprint reader
  services.fprintd.enable = true;
NIX
    fi

    if [[ "${ENABLE_THUNDERBOLT:-no}" == "yes" ]]; then
        has_peripherals=1
        cat << 'NIX'

  # Thunderbolt
  services.hardware.bolt.enable = true;
NIX
    fi

    if [[ "${ENABLE_SENSORS:-no}" == "yes" ]]; then
        has_peripherals=1
        cat << 'NIX'

  # IIO sensor proxy (2-in-1 tablets)
  hardware.sensor.iio.enable = true;
NIX
    fi

    if [[ "${ENABLE_WWAN:-no}" == "yes" ]]; then
        has_peripherals=1
        cat << 'NIX'

  # WWAN/LTE modem
  networking.modemmanager.enable = true;
NIX
    fi

    [[ ${has_peripherals} -eq 1 ]] && echo ""
}

_nix_audio() {
    cat << 'NIX'
  # --- Audio: PipeWire ---
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    wireplumber.enable = true;
  };
NIX

    echo ""
}

_nix_packages() {
    cat << 'NIX'
  # --- System packages ---
  environment.systemPackages = with pkgs; [
    # Core tools
    vim
    wget
    curl
    git
    htop
    unzip
    file
    pciutils
    usbutils
NIX

    # Hyprland ecosystem packages
    if [[ "${ENABLE_HYPRLAND:-no}" == "yes" ]]; then
        cat << 'NIX'
    # Hyprland ecosystem
    hyprpaper
    hypridle
    hyprlock
    waybar
    wofi
    mako
    grim
    slurp
    wl-clipboard
    brightnessctl
NIX
    fi

    # Desktop extras
    local extras="${DESKTOP_EXTRAS:-}"
    if [[ -n "${extras}" ]]; then
        local pkg
        local cleaned
        cleaned=$(echo "${extras}" | tr -d '"')
        for pkg in ${cleaned}; do
            echo "    ${pkg}"
        done
    fi

    # Extra packages from user
    if [[ -n "${EXTRA_PACKAGES:-}" ]]; then
        local pkg
        for pkg in ${EXTRA_PACKAGES}; do
            echo "    ${pkg}"
        done
    fi

    cat << 'NIX'
  ];
NIX

    if [[ "${ENABLE_FLATPAK:-no}" == "yes" ]]; then
        cat << 'NIX'

  # Flatpak
  services.flatpak.enable = true;
NIX
    fi

    echo ""
}

_nix_services() {
    cat << 'NIX'
  # --- Misc services ---
  services.fwupd.enable = true;
NIX

    if [[ "${ENABLE_ASUSCTL:-no}" == "yes" ]]; then
        cat << 'NIX'

  # ASUS ROG/TUF support
  services.asusd.enable = true;
  services.asusd.enableUserService = true;
NIX
    fi

    echo ""
}

_nix_settings() {
    if [[ "${USE_FLAKES:-yes}" == "yes" ]]; then
        cat << 'NIX'
  # --- Nix settings ---
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };
NIX
    else
        cat << 'NIX'
  # --- Nix settings ---
  nix.settings = {
    auto-optimise-store = true;
  };
NIX
    fi
    cat << 'NIX'

  # Garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  # Allow unfree packages (needed for NVIDIA drivers, vscode, etc.)
  nixpkgs.config.allowUnfree = true;  # TODO: make conditional on GPU_VENDOR=nvidia or unfree packages
NIX

    echo ""
}
